### ISSUE TITLE
Tried everything - CUDA not detected

### ISSUE THREAD

**Issue by madmax2052** [denizsafak/abogen#24]
Hi! Love the project. The thing with CUDA is actually a nothingburger, but maybe I'm doing something so obviously wrong, that you are able to help. Already did some troubleshooting with chatGPT.

I have a ASUS laptop running on windows 11 with a hybrid solution - AMD iGPU and a RTX 4060 dGPU. Already running just the dGPU. 
Got python - fresh install
import torch
print(torch.cuda.is_available()) was true. 
 
still: 

Checking GPU acceleration...
CUDA GPU is not available. Using CPU.

what did I miss?

:-(

**Comment by denizsafak** [comment]
@madmax2052

I recently made some changes. In Windows installer. are you using Windows installer? Can you try to run it again and show me the output screen at the end? (where it asks for creating shortcuts at the end)

**Comment by madmax2052** [comment]
![Image](https://github.com/user-attachments/assets/4eeec49b-78f5-4cc9-9f05-f9ed3b9a2f68)

**Comment by denizsafak** [comment]
That's weird. Can you go to `python_embedded` folder, open terminal in there and type:

````
./python.exe -m pip install torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu128 --no-warn-script-location
````

**Comment by madmax2052** [comment]
> That's weird. Can you go to `python_embedded` folder, open terminal in there and type:
> 
> ```
> ./python.exe -m pip install torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu128 --no-warn-script-location
> ```

**Comment by madmax2052** [comment]
Just did it.

:-(

did a reset. checked one more time if dGPU is properly activated. cuda.if_active still true.

**Comment by madmax2052** [comment]
did it. again got a message that the install was successful and CUDA was detected. Still while running the software I get 'no CUDA, going with CPU'

**Comment by madmax2052** [comment]
just as a sanity check I did the install again but with the iGPU. And the message at the end of the install was different, i.e. no Nvidia card was detected, skipping PyTorch. WILD.

**Comment by denizsafak** [comment]
@madmax2052 

Can you go to `python_embedded` and run `python.exe` directly, and type:

````
import torch
# after that, type
print(torch.cuda.is_available())
````
Does this still print true in there?

That's really weird. It should print true 🤔

**Comment by madmax2052** [comment]
it shows 'true'

**Comment by denizsafak** [comment]
> just as a sanity check I did the install again but with the iGPU. And the message at the end of the install was different, i.e. no Nvidia card was detected, skipping PyTorch. WILD.

iGPU mode disables your Nvidia GPU. So it should return that, no issues there. CUDA is not supported with AMD GPUs in Windows.

But dGPU or MsHybrid should work... It should detect your Nvidia GPU...

**Comment by madmax2052** [comment]
checked the torch version. 2.7.0+cu128 should be OK?

**Comment by denizsafak** [comment]
Not sure why it returns false. The program uses the same exact function to check your CUDA. (in utils.py, get_gpu_acceleration function)

Same function should not return differently.

Are you sure your "Use GPU acceleration" box is enabled in the abogen?

**Comment by denizsafak** [comment]
Did you use `pip install abogen`?

Seems like you somehow installed abogen in Python 3.13? Not sure...

Abogen suports Python 3.10 to 3.12.

I need to see the output of the Python in `python_embedded` folder. Just click `python.exe` in that folder. It's different

**Comment by madmax2052** [comment]
nah, used the windows_install

**Comment by madmax2052** [comment]
in python it shows me an syntax error, so I used the installer

>>> pip install abogen
  File "<python-input-1>", line 1
    pip install abogen
        ^^^^^^^
SyntaxError: invalid syntax

**Comment by madmax2052** [comment]
it actually does! wait... what?!

**Comment by madmax2052** [comment]
how did you now it would would print false?! it was true the whole time!

**Comment by madmax2052** [comment]
ok, as above - I'm VERY new to python. Installed it just to use your software. chatGPT explained the whole mystery to me. 

I do want to thank you for your time

**Comment by denizsafak** [comment]
@madmax2052 Because abogen uses that `python.exe` to start when you install with windows installer, not the Python installed in your computer. It is called embedded python. It's like a seperate Python environment in a folder.

It should print false because same function prints false and you see "GPU not avaliable" error in log window.

My best guess is:
It couldn't install TORCH when you're installing it the first time.

- You can try deleting "python_embedded" folder and try again.

- You can try installing PyTorch by:

Right click in `python_embedded` folder, click `Open terminal in this folder`

Type:

```
./python.exe -m pip install torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu128 --no-warn-script-location
```

This will install TORCH in correct Python environment.

So you don't need Python, if you don't use it, you can uninstall, becauae Windows installer already installs Python in python_embedded folder and abogen uses that Python, not the Python installed on your computer.

**Comment by madmax2052** [comment]
My dear sir, may I present to you:

![Image](https://github.com/user-attachments/assets/5076d9f3-9f36-43e3-91bf-a381f0ccec35)

:D:D:D

**Comment by denizsafak** [comment]
Finally 😄 Which method did you use?

**Comment by madmax2052** [comment]
I used the solution you gave me with installing torch in the python embedded folder (with the terminal). Worked like a charm :D Didn't even have to restart or anything. 

Is there a chance for support for polish?

**Comment by denizsafak** [comment]
@madmax2052 You'll need to open issue in Kokoro:
https://github.com/hexgrad/kokoro

Abogen is using Kokoro at the background for voice generation.

I'm not the maintainer of Kokoro, so I can't help with lanugages, sorry about that 🙂

**Comment by alx** [comment]
Because this thread helped me fix CUDA not detected using uv, you need to set venv with a compatible version of python:

`uv venv --python 3.11 --seed
