### ISSUE TITLE
CUDA GPU is not available. Using CPU.

### ISSUE THREAD

**Issue by Sevallis** [denizsafak/abogen#32]
Hi, I'm on Windows 11 Pro 23H2 , and I installed eSpeak via MSI file and Abogen via Windows script, and when I run a book it tells me that CUDA is not available even though I have a 5070ti. I didn't notice any errors about CUDA during the install terminal text. Any idea how to get it to accelerate creation with my GPU?

**Comment by denizsafak** [comment]
Please go to abogen's folder, open terminal and type:

``
python_embedded\python.exe -m pip install gpustat && python_embedded\python.exe main\is_nvidia.py
``

and show me the output at the end

**Comment by denizsafak** [comment]
What about this
````
python_embedded\python.exe -m pip install gpustat; python_embedded\python.exe main\is_nvidia.py
````

**Comment by denizsafak** [comment]
Hmm, okay. Now type:
````
python_embedded\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
````
And try again

**Comment by Sevallis** [comment]
Seemed fine, but this appears relevant:

```
Downloading https://download.pytorch.org/whl/cu128/torchvision-0.22.1%2Bcu128-cp312-cp312-win_amd64.whl (7.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 52.7 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cu128/torch-2.7.1%2Bcu128-cp312-cp312-win_amd64.whl (3273.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 GB 32.0 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cu128/torchaudio-2.7.1%2Bcu128-cp312-cp312-win_amd64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 70.9 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/pillow-11.0.0-cp312-cp312-win_amd64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 49.1 MB/s eta 0:00:00
Installing collected packages: pillow, torch, torchvision, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.7.1
    Uninstalling torch-2.7.1:
      Successfully uninstalled torch-2.7.1
   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/4 [torch]  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\Users\username\Downloads\abogen-main\abogen-main\python_embedded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pillow-11.0.0 torch-2.7.1+cu128 torchaudio-2.7.1+cu128 torchvision-0.22.1+cu128
```

**Comment by jefro108** [comment]
I see now that in the code 

```
# Enable MPS GPU acceleration on Mac Apple Silicon
if platform.system() == "Darwin" and platform.processor() == "arm":
    os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
```
it should work for Mac Apple Silicon

I've installed `torch torchvision torchaudio` so what else do I need to do to make it work on a Mac?

**Comment by denizsafak** [comment]
@jefro108 The “CUDA available” message only appears when the system detects a compatible NVIDIA GPU with CUDA support (or in some cases, an AMD GPU with ROCm). 

Since macOS doesn't support either CUDA or ROCm, you won’t see that message on a Mac. While your Mac will still be able to run the program, it’ll do so using the CPU or Apple's own GPU architecture, which works, but won’t offer the same performance as a dedicated CUDA-capable GPU.

So everything should still function, just with reduced acceleration compared to systems with NVIDIA or AMD GPU support.

**Comment by jefro108** [comment]
Yes I realise all that but it appears that with PyTorch installed it is possible to get GPU acceleration and you have that code that gets PyTorch to use mps instead of cuda?

Like from https://stackoverflow.com/a/72401340

```
device = torch.device('mps')

# Send you tensor to GPU
my_tensor = my_tensor.to(device)
```

However I can’t see where you refer to cuda in the code, but you do say `Enable MPS GPU acceleration on Mac Apple Silicon` in your code in line 53 of main.py. 

So I’m confused by your last statement 🤔

**Comment by jefro108** [comment]
Or is the GPU Acceleration happening anyway? But there’s no notification of it? 😊

**Comment by denizsafak** [comment]
Looks like Kokoro [has a commit](https://github.com/hexgrad/kokoro/commit/6d87f4ae7abc2d14dbc4b3ef2e5f19852e861ac2) about MPS support (in April) for Apple Silicon, but the new version has not released yet. So unfortunately, the current version (0.9.4) does not support MPS yet.

## But there might be a temporary solution
Until Kokoro's new version releases, you can **(maybe)** use this solution:

```bash
# This is very similar to installing abogen.

# Create a virtual environment (recommended)
mkdir abogen-mps && cd abogen-mps
python3 -m venv venv
source venv/bin/activate

# Install abogen (This is a new branch with future MPS support)
pip install git+https://github.com/denizsafak/abogen@apple

# Install kokoro (developement)
pip install git+https://github.com/hexgrad/kokoro.git

# Run abogen
abogen
```

In theory, it should work. I don't have a Mac so I can't test. So please test and give me the results.

**Comment by jefro108** [comment]
Thanks. I did as you suggested. However I found that when I used the new code with a short document compared with the current version that it actually took longer at 'Time elapsed: 00:01:29'  vs 'Time elapsed: 00:01:04' which was curious.

Details:
- File size: 3.04 KB
- Total characters: 2,723
- Language: a (American English)
- Voice: af_nova
- Speed: 1.05
- Subtitle mode: Disabled
- Output format: m4b
- Subtitle format: ASS (centered narrow)
- Save option: Save to Desktop
- Save chapters separately: No

**Comment by denizsafak** [comment]
@jefro108 hmm, so MPS is not good enough, or Kokoro needs to improve its performance. There is nothing I can do. Thanks 👍

**Comment by SkippyTheWonderBot** [comment]
> [@SkippyTheWonderBot](https://github.com/SkippyTheWonderBot) That’s interesting 🤔 Could you share the time differences? Sometimes the estimated times don’t match the actual completion time.

Urgh. The cloudd process is hogging my cpu at around 200%, which is making my runs inconsistent. 

With MPS, one chapter (2700 characters) completed in 2:15. CPU was at around 90% and GPU around 90%.
Without MPS, CPU was around 300% and took over 4 mins.

But, then I tried with MPS again and it took over 6 mins. Given the cloudd deamon is lightly thrashing my system. (Macs are not magic are they...) I'm not absolutely sure of anything yet. 

Energy wise, mps acceleration does seem like it helping.

I'll keep on trying, when (or if) cloudd stops forking me about.

**Comment by denizsafak** [comment]
Hey @jorgeperezlara, that command is for checking if you have an NVIDIA GPU or not. In Linux, sometimes it says "CUDA is not available" for me too. I'm not sure why, but restarting the app solves the issue.

**Comment by denizsafak** [comment]
# UPDATE

> [!IMPORTANT]
> **MPS Support is added in v1.1.7. The `Apple` branch will not be updated and it will be removed. If you are using v1.1.6, please update abogen and read the [Mac](https://github.com/denizsafak/abogen?tab=readme-ov-file#mac) section in the documentation again, as it requires additional configuration.**

**Comment by benjaminebatoria-dot** [comment]
> Hmm, okay. Now type:
> 
> ```
> python_embedded\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> ```
> 
> And try again

WORKS! On my RTX 5090 it took 13 seconds of 28 min text! Thank you!

**Comment by kgeo** [comment]
I am on Win 11 and have an 1050 Ti that does have CUDA. I did get the 
`CUDA GPU is not available. Using CPU. (No devices found)`
error and followed the FAQ advise and ran 
`python_embedded\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`
which seemingly ran ok.

However, now when I try to start a translation, I get:

`Checking GPU acceleration...
CUDA GPU is not available. Using CPU. (No devices found)
Loading modules...
Error loading numpy or KPipeline: Could not import module 'AlbertModel'. Are this object's requirements defined correctly?`

What can I do?

**Comment by kgeo** [comment]
Also I got worried that because of my old GPU the supported CUDA might be old as well, but nvidia-smi gives me the below, which sounds ok to me.

<img width="823" height="200" alt="Image" src="https://github.com/user-attachments/assets/f282e5e6-27c7-4f5f-b762-b7548fceab86" />

**Comment by denizsafak** [comment]
@kgeo Hmm, what about this one?
````
python_embedded\python.exe -m pip install torch==2.8.0 torchaudio==2.8.0 torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cu126
````

It is cuda 12.6 instead of 12.8.

**Comment by denizsafak** [comment]
@kgeo I'll check if that's possible, thanks 😋

**Comment by kuhekin** [comment]
Got into the same problem as @kgeo 
Downgraded to cu126 worked for me!
3050ti Laptop

**Comment by Ony-K** [comment]
> > [@Sevallis](https://github.com/Sevallis) can you try with older cuda? for example:
> > ```
> > python_embedded\python.exe -m pip install --force-reinstall torch==2.8.0+cu126 torchvision==0.23.0+cu126 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu126
> > ```
> 
> Ran that and it was all successful except one minor error `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. supertonic 1.1.2 requires numpy<2.0,>=1.21.0, but you have numpy 2.3.5 which is incompatible.` but I don't care since I'm not trying to use that.
> 
> Still get the same CUDA GPU available and enabled but the identical error about failing to initialize model on CUDA that I previously posted when I run the book to audio conversion.
> 
> Partial solution EDIT: Decided to try another version `python_embedded\python.exe -m pip install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128` and I no longer get the pipeline error. However, for some reason it loads the chapters but doesn't progress. No errors, it just gets stuck.
> 
> Edit 2, Full Solution: Fresh install 1.2.5, ran `python_embedded\python.exe -m pip install --force-reinstall torch==2.8.0+cu128 torchvision==0.23.0+cu128 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu128` in the root program folder via terminal just in case (I think it was already installed from my last attempt) This is working 100% on my computer. I have a conversion running right now with 20-40% GPU utilized for acceleration.

This has worked for me to install 1.2.5 on my setup Windows 11 24H2, AMD Ryzen 7 8-Core Processor, RTX 3080
